<?php

/**
 * InvoicePlane application constants.
 *
 * Defines the feature flags, environment / error-reporting mode and the
 * writable-path constants that the application relies on. This file is loaded
 * by kernel.php once the environment (ipconfig.php) and the env() / env_bool()
 * helpers are available.
 *
 * All paths are anchored to IP_ROOTPATH — the project root — so that the
 * application code, configuration and writable data continue to live outside
 * the public/ document root.
 *
 * DO NOT EDIT THIS FILE for configuration. Copy ipconfig.php.example to
 * ipconfig.php and set your options there.
 */

if ( ! defined('IP_ROOTPATH')) {
    exit('IP_ROOTPATH is not defined; bootstrap/constants.php must be loaded via kernel.php.');
}

/*
 *---------------------------------------------------------------
 * FEATURE FLAGS
 *---------------------------------------------------------------
 */

// Enable debug mode if set
defined('IP_DEBUG') || define('IP_DEBUG', env_bool('ENABLE_DEBUG'));
// Settings Invoices Sumex panel - Since v1.6.3
defined('SUMEX_SETTINGS') || define('SUMEX_SETTINGS', env_bool('SUMEX_SETTINGS'));
// Where to post sumex xml to get pdf - Since v1.5.0 - See InvoicePlane/InvoicePlane#453
defined('SUMEX_URL') || define('SUMEX_URL', env('SUMEX_URL'));

/*
 *---------------------------------------------------------------
 * APPLICATION ENVIRONMENT
 *---------------------------------------------------------------
 *
 * You can load different configurations depending on your current
 * environment. Setting the environment also influences things like logging
 * and error reporting.
 *
 * NOTE: If you change these, also change the error_reporting() code below.
 */
defined('ENVIRONMENT') || define('ENVIRONMENT', $_SERVER['CI_ENV'] ?? 'development');

/*
 *---------------------------------------------------------------
 * ERROR REPORTING
 *---------------------------------------------------------------
 *
 * Different environments will require different levels of error reporting.
 * By default development will show errors but testing and live will hide them.
 */
switch (ENVIRONMENT) {
    case 'development':
        error_reporting(-1);
        ini_set('display_errors', 1);
        break;

    case 'testing':
    case 'production':
        ini_set('display_errors', 0);
        error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_NOTICE & ~E_USER_DEPRECATED);
        break;

    default:
        header('HTTP/1.1 503 Service Unavailable.', true, 503);
        echo 'The application environment is not set correctly.';
        exit(1); // EXIT_ERROR
}

/*
 *---------------------------------------------------------------
 * PATH CONSTANTS
 *---------------------------------------------------------------
 *
 * The application code, configuration and writable data all live at the
 * project root (IP_ROOTPATH), one level above the public/ document root.
 */
defined('IPCONFIG_FILE') || define('IPCONFIG_FILE', IP_ROOTPATH . DIRECTORY_SEPARATOR . 'ipconfig.php');

defined('LOGS_FOLDER') || define('LOGS_FOLDER', IP_ROOTPATH . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR . 'logs' . DIRECTORY_SEPARATOR);

defined('UPLOADS_FOLDER') || define('UPLOADS_FOLDER', IP_ROOTPATH . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR);
defined('UPLOADS_ARCHIVE_FOLDER') || define('UPLOADS_ARCHIVE_FOLDER', UPLOADS_FOLDER . 'archive' . DIRECTORY_SEPARATOR);
defined('UPLOADS_CFILES_FOLDER') || define('UPLOADS_CFILES_FOLDER', UPLOADS_FOLDER . 'customer_files' . DIRECTORY_SEPARATOR);
defined('UPLOADS_TEMP_FOLDER') || define('UPLOADS_TEMP_FOLDER', UPLOADS_FOLDER . 'temp' . DIRECTORY_SEPARATOR);
defined('UPLOADS_TEMP_MPDF_FOLDER') || define('UPLOADS_TEMP_MPDF_FOLDER', UPLOADS_TEMP_FOLDER . 'mpdf' . DIRECTORY_SEPARATOR);

defined('STORAGE_TEMP_FOLDER') || define('STORAGE_TEMP_FOLDER', IP_ROOTPATH . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'temp' . DIRECTORY_SEPARATOR);

defined('THEME_FOLDER') || define('THEME_FOLDER', IP_ROOTPATH . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR);

$_custom_tpl = env('CUSTOM_TEMPLATES_FOLDER');
defined('CUSTOM_TEMPLATES_FOLDER') || define('CUSTOM_TEMPLATES_FOLDER', $_custom_tpl ? rtrim($_custom_tpl, '/\\') . DIRECTORY_SEPARATOR : null);
unset($_custom_tpl);

/*
 *---------------------------------------------------------------
 * WRITABLE STORAGE + TEMP FILE CLEANUP
 *---------------------------------------------------------------
 */

// Ensure storage temp directory exists
if ( ! is_dir(STORAGE_TEMP_FOLDER)) {
    @mkdir(STORAGE_TEMP_FOLDER, 0755, true);
}

// Automatic temp pdf & xml files cleanup
$_temp_files = array_merge(
    glob(UPLOADS_TEMP_FOLDER . '*.pdf') ?: [],
    glob(UPLOADS_TEMP_FOLDER . '*.xml') ?: [],
    glob(STORAGE_TEMP_FOLDER . '*.xml') ?: []
);

array_map('unlink', array_filter($_temp_files, 'is_file'));
unset($_temp_files);
