<?php

/**
 * InvoicePlane bootstrap kernel.
 *
 * Shared front-controller bootstrap. It loads the environment configuration
 * (ipconfig.php via Dotenv), defines the application constants (see
 * bootstrap/constants.php) and the CodeIgniter path constants, then hands
 * control to CodeIgniter.
 *
 * The front controller (public/index.php) must define IP_ROOTPATH — the
 * project root, one level above the public/ document root — before including
 * this file, and may define IP_WEBROOT (the document root directory). When
 * included directly both fall back to this file's own directory.
 *
 * DO NOT EDIT THIS FILE for configuration. Copy ipconfig.php.example to
 * ipconfig.php and set your options there.
 */

if ( ! defined('IP_ROOTPATH')) {
    define('IP_ROOTPATH', __DIR__);
}

/*
 *---------------------------------------------------------------
 * LOAD ENVIRONMENT (ipconfig.php via Dotenv)
 *---------------------------------------------------------------
 */
if ( ! file_exists(IP_ROOTPATH . DIRECTORY_SEPARATOR . 'ipconfig.php')) {
    exit('The <b>ipconfig.php</b> file is missing! Please make a copy of the <b>ipconfig.php.example</b> file and rename it to <b>ipconfig.php</b>');
}

require IP_ROOTPATH . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(IP_ROOTPATH, 'ipconfig.php');
$dotenv->load();

/**
 * Small helper function to allow defaults for the getenv function.
 *
 * Guarded with function_exists() so the kernel can coexist with the legacy
 * root index.php (which declares the same helpers) inside a single PHP
 * process, e.g. under CLI.
 *
 * @param string $env_key
 * @param mixed  $default
 *
 * @return mixed
 */
if ( ! function_exists('env')) {
    function env($env_key, $default = null)
    {
        if (isset($_ENV[$env_key])) {
            return $_ENV[$env_key];
        }

        return $default;
    }
}

/**
 * Small helper function to get bool values for the env setting.
 *
 * @param string $env_key
 * @param string $default
 */
if ( ! function_exists('env_bool')) {
    function env_bool($env_key, $default = 'false'): bool
    {
        return env($env_key, $default) === 'true';
    }
}

/*
 *---------------------------------------------------------------
 * APPLICATION CONSTANTS + ENVIRONMENT / ERROR REPORTING
 *---------------------------------------------------------------
 */
require IP_ROOTPATH . DIRECTORY_SEPARATOR . 'bootstrap' . DIRECTORY_SEPARATOR . 'constants.php';

/*
 *---------------------------------------------------------------
 * CODEIGNITER PATHS
 *---------------------------------------------------------------
 *
 * The system and application directories live at the project root, alongside
 * (not inside) the public/ document root.
 */
$system_path        = IP_ROOTPATH . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'pocketarc' . DIRECTORY_SEPARATOR . 'codeigniter' . DIRECTORY_SEPARATOR . 'system';
$application_folder = IP_ROOTPATH . DIRECTORY_SEPARATOR . 'application';
$view_folder        = '';

// Set the current directory correctly for CLI requests
if (defined('STDIN')) {
    chdir(__DIR__);
}

// Resolve the system path for increased reliability
if (($_temp = realpath($system_path)) !== false) {
    $system_path = $_temp . DIRECTORY_SEPARATOR;
} else {
    $system_path = rtrim($system_path, '/\\') . DIRECTORY_SEPARATOR;
}

if ( ! is_dir($system_path)) {
    header('HTTP/1.1 503 Service Unavailable.', true, 503);
    echo 'Your system folder path does not appear to be set correctly.';
    exit(3); // EXIT_CONFIG
}

// Resolve the application path
if (($_temp = realpath($application_folder)) !== false) {
    $application_folder = $_temp;
} else {
    $application_folder = rtrim($application_folder, '/\\');
}

if ( ! is_dir($application_folder)) {
    header('HTTP/1.1 503 Service Unavailable.', true, 503);
    echo 'Your application folder path does not appear to be set correctly.';
    exit(3); // EXIT_CONFIG
}

/*
 * -------------------------------------------------------------------
 *  Now that we know the paths, set the main path constants
 * -------------------------------------------------------------------
 */
// The name of the front controller
define('SELF', 'index.php');

// Path to the system directory
define('BASEPATH', $system_path);

// Path to the front controller (the document root) directory
define('FCPATH', rtrim(defined('IP_WEBROOT') ? IP_WEBROOT : __DIR__, '/\\') . DIRECTORY_SEPARATOR);

// Name of the "system" directory
define('SYSDIR', basename(rtrim(BASEPATH, DIRECTORY_SEPARATOR)));

// The path to the "application" directory
define('APPPATH', $application_folder . DIRECTORY_SEPARATOR);

// The path to the "views" directory
if ( ! isset($view_folder[0]) && is_dir(APPPATH . 'views' . DIRECTORY_SEPARATOR)) {
    $view_folder = APPPATH . 'views';
} elseif (is_dir($view_folder)) {
    $view_folder = realpath($view_folder) ?: rtrim($view_folder, '/\\');
} elseif (is_dir(APPPATH . $view_folder . DIRECTORY_SEPARATOR)) {
    $view_folder = APPPATH . rtrim($view_folder, '/\\');
} else {
    header('HTTP/1.1 503 Service Unavailable.', true, 503);
    echo 'Your view folder path does not appear to be set correctly.';
    exit(3); // EXIT_CONFIG
}

define('VIEWPATH', $view_folder . DIRECTORY_SEPARATOR);

/*
 * --------------------------------------------------------------------
 * LOAD THE BOOTSTRAP FILE
 * --------------------------------------------------------------------
 *
 * And away we go...
 */
require_once BASEPATH . 'core' . DIRECTORY_SEPARATOR . 'CodeIgniter.php';
