#!/bin/bash
set -e

# Lighter counterpart to resources/docker/entrypoint.sh (used by compose.yml's
# self-contained image). Differences, on purpose:
#   - Only generates ipconfig.php if one doesn't already exist — your edits
#     are never overwritten on a restart, unlike the production entrypoint.
#   - Never sets DISABLE_SETUP — the web setup wizard stays reachable, since
#     this container exists for developing/testing InvoicePlane itself.
#   - Takes the app root as a variable (APP_ROOT) instead of assuming
#     /var/www/html, since docker-compose.yml bind-mounts the working tree to
#     /var/www/projects/invoiceplane instead.

APP_ROOT="${APP_ROOT:-/var/www/projects/invoiceplane}"
CONFIG="$APP_ROOT/ipconfig.php"

sanitize_config_value() {
    local value="$1"
    case "$value" in
        *$'\n'* | *$'\r'*)
            echo "Error: configuration value must not contain newline or carriage-return characters." >&2
            exit 1
            ;;
    esac
    printf '%s' "$value"
}

if [ -f "$CONFIG" ]; then
    echo "ipconfig.php already exists at $CONFIG — leaving it untouched."
else
    echo "No ipconfig.php found at $CONFIG — generating one from environment variables."

    : "${IP_URL:?IP_URL is required (e.g. http://ivpl.local)}"
    : "${DB_HOSTNAME:?DB_HOSTNAME is required}"
    : "${DB_USERNAME:?DB_USERNAME is required}"
    : "${DB_PASSWORD:?DB_PASSWORD is required}"
    : "${DB_DATABASE:?DB_DATABASE is required}"
    : "${ENCRYPTION_KEY:?ENCRYPTION_KEY is required — generate with: openssl rand -base64 32}"

    IP_URL_SAFE="$(sanitize_config_value "$IP_URL")"
    DB_HOSTNAME_SAFE="$(sanitize_config_value "$DB_HOSTNAME")"
    DB_USERNAME_SAFE="$(sanitize_config_value "$DB_USERNAME")"
    DB_PASSWORD_SAFE="$(sanitize_config_value "$DB_PASSWORD")"
    DB_DATABASE_SAFE="$(sanitize_config_value "$DB_DATABASE")"
    DB_PORT_SAFE="$(sanitize_config_value "${DB_PORT:-3306}")"
    CI_ENV_SAFE="$(sanitize_config_value "${CI_ENV:-development}")"
    ENCRYPTION_KEY_SAFE="$(sanitize_config_value "$ENCRYPTION_KEY")"
    ENCRYPTION_CIPHER_SAFE="$(sanitize_config_value "${ENCRYPTION_CIPHER:-AES-256}")"

    cat > "$CONFIG" <<EOF
# <?php exit('No direct script access allowed'); ?>
# InvoicePlane Configuration File — generated by dev-entrypoint.sh
#
# Unlike compose.yml's production entrypoint, this file is generated ONCE and
# then left alone. Edit it directly for anything not covered below (e.g.
# CSRF_REGENERATE, SESS_SAVE_PATH) — your changes will persist across restarts.

IP_URL=${IP_URL_SAFE}

CI_ENV=${CI_ENV_SAFE}
ENABLE_DEBUG=true

DB_HOSTNAME=${DB_HOSTNAME_SAFE}
DB_USERNAME=${DB_USERNAME_SAFE}
DB_PASSWORD=${DB_PASSWORD_SAFE}
DB_DATABASE=${DB_DATABASE_SAFE}
DB_PORT=${DB_PORT_SAFE}

ENCRYPTION_KEY=${ENCRYPTION_KEY_SAFE}
ENCRYPTION_CIPHER=${ENCRYPTION_CIPHER_SAFE}
EOF

    # This container runs as root, so a freshly generated file would
    # otherwise land root-owned on the bind-mounted host directory. PUID/PGID
    # already exist as build args for exactly this class of problem (they
    # also set www-data's uid/gid) — reuse them here for consistency.
    chown "${PUID:-1000}:${PGID:-1000}" "$CONFIG" 2>/dev/null || true

    echo "Generated $CONFIG"
fi

# Best-effort: apply any pending schema migrations. Safe to run on every
# start (idempotent) but not fatal if it fails — e.g. the database may not
# be initialized yet if you haven't been through /index.php/setup, and
# DISABLE_SETUP is never forced here, so that's a normal state to be in.
if [ -f "$APP_ROOT/public/index.php" ]; then
    if ! (cd "$APP_ROOT" && php public/index.php setup/cli/migrate); then
        echo "WARNING: migration step failed — normal if the app hasn't been through /setup yet. Continuing." >&2
    fi
fi

exec "$@"
