<?php declare(strict_types = 1);

// osfsl-/var/www/projects/exprmt/vendor/composer/../stripe/stripe-php/lib/Subscription.php-PHPStan\BetterReflection\Reflection\ReflectionClass-Stripe\Subscription
return \PHPStan\Cache\CacheItem::__set_state(array(
   'variableKey' => 'v2-4dda30ef5f801733b2f89a701a318b7aa1471a2295e0dc1da14326f6b1ecd2c5-8.4.24-6.70.0.3',
   'data' => 
  array (
    'locatedSource' => 
    array (
      'class' => 'PHPStan\\BetterReflection\\SourceLocator\\Located\\LocatedSource',
      'data' => 
      array (
        'name' => 'Stripe\\Subscription',
        'filename' => '/var/www/projects/exprmt/vendor/composer/../stripe/stripe-php/lib/Subscription.php',
      ),
    ),
    'namespace' => 'Stripe',
    'name' => 'Stripe\\Subscription',
    'shortName' => 'Subscription',
    'isInterface' => false,
    'isTrait' => false,
    'isEnum' => false,
    'isBackedEnum' => false,
    'modifiers' => 0,
    'docComment' => '/**
 * Subscriptions allow you to charge a customer on a recurring basis.
 *
 * Related guide: <a href="https://stripe.com/docs/billing/subscriptions/creating">Creating subscriptions</a>
 *
 * @property string $id Unique identifier for the object.
 * @property string $object String representing the object\'s type. Objects of the same type share the same value.
 * @property null|string|\\Stripe\\Application $application ID of the Connect Application that created the subscription.
 * @property null|float $application_fee_percent A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the application owner\'s Stripe account.
 * @property \\Stripe\\StripeObject $automatic_tax
 * @property int $billing_cycle_anchor The reference point that aligns future <a href="https://stripe.com/docs/subscriptions/billing-cycle">billing cycle</a> dates. It sets the day of week for <code>week</code> intervals, the day of month for <code>month</code> and <code>year</code> intervals, and the month of year for <code>year</code> intervals. The timestamp is in UTC format.
 * @property null|\\Stripe\\StripeObject $billing_cycle_anchor_config The fixed values used to calculate the <code>billing_cycle_anchor</code>.
 * @property null|\\Stripe\\StripeObject $billing_thresholds Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period
 * @property null|int $cancel_at A date in the future at which the subscription will automatically get canceled
 * @property bool $cancel_at_period_end If the subscription has been canceled with the <code>at_period_end</code> flag set to <code>true</code>, <code>cancel_at_period_end</code> on the subscription will be true. You can use this attribute to determine whether a subscription that has a status of active is scheduled to be canceled at the end of the current period.
 * @property null|int $canceled_at If the subscription has been canceled, the date of that cancellation. If the subscription was canceled with <code>cancel_at_period_end</code>, <code>canceled_at</code> will reflect the time of the most recent update request, not the end of the subscription period when the subscription is automatically moved to a canceled state.
 * @property null|\\Stripe\\StripeObject $cancellation_details Details about why this subscription was cancelled
 * @property string $collection_method Either <code>charge_automatically</code>, or <code>send_invoice</code>. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions and mark the subscription as <code>active</code>.
 * @property int $created Time at which the object was created. Measured in seconds since the Unix epoch.
 * @property string $currency Three-letter <a href="https://www.iso.org/iso-4217-currency-codes.html">ISO currency code</a>, in lowercase. Must be a <a href="https://stripe.com/docs/currencies">supported currency</a>.
 * @property int $current_period_end End of the current period that the subscription has been invoiced for. At the end of this period, a new invoice will be created.
 * @property int $current_period_start Start of the current period that the subscription has been invoiced for.
 * @property string|\\Stripe\\Customer $customer ID of the customer who owns the subscription.
 * @property null|int $days_until_due Number of days a customer has to pay invoices generated by this subscription. This value will be <code>null</code> for subscriptions where <code>collection_method=charge_automatically</code>.
 * @property null|string|\\Stripe\\PaymentMethod $default_payment_method ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over <code>default_source</code>. If neither are set, invoices will use the customer\'s <a href="https://stripe.com/docs/api/customers/object#customer_object-invoice_settings-default_payment_method">invoice_settings.default_payment_method</a> or <a href="https://stripe.com/docs/api/customers/object#customer_object-default_source">default_source</a>.
 * @property null|string|\\Stripe\\Account|\\Stripe\\BankAccount|\\Stripe\\Card|\\Stripe\\Source $default_source ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If <code>default_payment_method</code> is also set, <code>default_payment_method</code> will take precedence. If neither are set, invoices will use the customer\'s <a href="https://stripe.com/docs/api/customers/object#customer_object-invoice_settings-default_payment_method">invoice_settings.default_payment_method</a> or <a href="https://stripe.com/docs/api/customers/object#customer_object-default_source">default_source</a>.
 * @property null|\\Stripe\\TaxRate[] $default_tax_rates The tax rates that will apply to any subscription item that does not have <code>tax_rates</code> set. Invoices created will have their <code>default_tax_rates</code> populated from the subscription.
 * @property null|string $description The subscription\'s description, meant to be displayable to the customer. Use this field to optionally store an explanation of the subscription for rendering in Stripe surfaces and certain local payment methods UIs.
 * @property null|\\Stripe\\Discount $discount Describes the current discount applied to this subscription, if there is one. When billing, a discount applied to a subscription overrides a discount applied on a customer-wide basis. This field has been deprecated and will be removed in a future API version. Use <code>discounts</code> instead.
 * @property (string|\\Stripe\\Discount)[] $discounts The discounts applied to the subscription. Subscription item discounts are applied before subscription discounts. Use <code>expand[]=discounts</code> to expand each discount.
 * @property null|int $ended_at If the subscription has ended, the date the subscription ended.
 * @property \\Stripe\\StripeObject $invoice_settings
 * @property \\Stripe\\Collection<\\Stripe\\SubscriptionItem> $items List of subscription items, each with an attached price.
 * @property null|string|\\Stripe\\Invoice $latest_invoice The most recent invoice this subscription has generated.
 * @property bool $livemode Has the value <code>true</code> if the object exists in live mode or the value <code>false</code> if the object exists in test mode.
 * @property \\Stripe\\StripeObject $metadata Set of <a href="https://stripe.com/docs/api/metadata">key-value pairs</a> that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
 * @property null|int $next_pending_invoice_item_invoice Specifies the approximate timestamp on which any pending invoice items will be billed according to the schedule provided at <code>pending_invoice_item_interval</code>.
 * @property null|string|\\Stripe\\Account $on_behalf_of The account (if any) the charge was made on behalf of for charges associated with this subscription. See the Connect documentation for details.
 * @property null|\\Stripe\\StripeObject $pause_collection If specified, payment collection for this subscription will be paused. Note that the subscription status will be unchanged and will not be updated to <code>paused</code>. Learn more about <a href="/billing/subscriptions/pause-payment">pausing collection</a>.
 * @property null|\\Stripe\\StripeObject $payment_settings Payment settings passed on to invoices created by the subscription.
 * @property null|\\Stripe\\StripeObject $pending_invoice_item_interval Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling <a href="https://stripe.com/docs/api#create_invoice">Create an invoice</a> for the given subscription at the specified interval.
 * @property null|string|\\Stripe\\SetupIntent $pending_setup_intent You can use this <a href="https://stripe.com/docs/api/setup_intents">SetupIntent</a> to collect user authentication when creating a subscription without immediate payment or updating a subscription\'s payment method, allowing you to optimize for off-session payments. Learn more in the <a href="https://stripe.com/docs/billing/migration/strong-customer-authentication#scenario-2">SCA Migration Guide</a>.
 * @property null|\\Stripe\\StripeObject $pending_update If specified, <a href="https://stripe.com/docs/billing/subscriptions/pending-updates">pending updates</a> that will be applied to the subscription once the <code>latest_invoice</code> has been paid.
 * @property null|string|\\Stripe\\SubscriptionSchedule $schedule The schedule attached to the subscription
 * @property int $start_date Date when the subscription was first created. The date might differ from the <code>created</code> date due to backdating.
 * @property string $status <p>Possible values are <code>incomplete</code>, <code>incomplete_expired</code>, <code>trialing</code>, <code>active</code>, <code>past_due</code>, <code>canceled</code>, <code>unpaid</code>, or <code>paused</code>.</p><p>For <code>collection_method=charge_automatically</code> a subscription moves into <code>incomplete</code> if the initial payment attempt fails. A subscription in this status can only have metadata and default_source updated. Once the first invoice is paid, the subscription moves into an <code>active</code> status. If the first invoice is not paid within 23 hours, the subscription transitions to <code>incomplete_expired</code>. This is a terminal status, the open invoice will be voided and no further invoices will be generated.</p><p>A subscription that is currently in a trial period is <code>trialing</code> and moves to <code>active</code> when the trial period is over.</p><p>A subscription can only enter a <code>paused</code> status <a href="/billing/subscriptions/trials#create-free-trials-without-payment">when a trial ends without a payment method</a>. A <code>paused</code> subscription doesn\'t generate invoices and can be resumed after your customer adds their payment method. The <code>paused</code> status is different from <a href="/billing/subscriptions/pause-payment">pausing collection</a>, which still generates invoices and leaves the subscription\'s status unchanged.</p><p>If subscription <code>collection_method=charge_automatically</code>, it becomes <code>past_due</code> when payment is required but cannot be paid (due to failed payment or awaiting additional user actions). Once Stripe has exhausted all payment retry attempts, the subscription will become <code>canceled</code> or <code>unpaid</code> (depending on your subscriptions settings).</p><p>If subscription <code>collection_method=send_invoice</code> it becomes <code>past_due</code> when its invoice is not paid by the due date, and <code>canceled</code> or <code>unpaid</code> if it is still not paid by an additional deadline after that. Note that when a subscription has a status of <code>unpaid</code>, no subsequent invoices will be attempted (invoices will be created, but then immediately automatically closed). After receiving updated payment information from a customer, you may choose to reopen and pay their closed invoices.</p>
 * @property null|string|\\Stripe\\TestHelpers\\TestClock $test_clock ID of the test clock this subscription belongs to.
 * @property null|\\Stripe\\StripeObject $transfer_data The account (if any) the subscription\'s payments will be attributed to for tax reporting, and where funds from each payment will be transferred to for each of the subscription\'s invoices.
 * @property null|int $trial_end If the subscription has a trial, the end of that trial.
 * @property null|\\Stripe\\StripeObject $trial_settings Settings related to subscription trials.
 * @property null|int $trial_start If the subscription has a trial, the beginning of that trial.
 */',
    'attributes' => 
    array (
    ),
    'startLine' => 59,
    'endLine' => 307,
    'startColumn' => 1,
    'endColumn' => 1,
    'parentClassName' => 'Stripe\\ApiResource',
    'implementsClassNames' => 
    array (
    ),
    'traitClassNames' => 
    array (
      0 => 'Stripe\\ApiOperations\\Search',
      1 => 'Stripe\\ApiOperations\\Update',
      2 => 'Stripe\\ApiOperations\\Delete',
    ),
    'immediateConstants' => 
    array (
      'OBJECT_NAME' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'OBJECT_NAME',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'subscription\'',
          'attributes' => 
          array (
            'startLine' => 61,
            'endLine' => 61,
            'startTokenPos' => 27,
            'startFilePos' => 12181,
            'endTokenPos' => 27,
            'endFilePos' => 12194,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 61,
        'endLine' => 61,
        'startColumn' => 5,
        'endColumn' => 39,
      ),
      'COLLECTION_METHOD_CHARGE_AUTOMATICALLY' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'COLLECTION_METHOD_CHARGE_AUTOMATICALLY',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'charge_automatically\'',
          'attributes' => 
          array (
            'startLine' => 66,
            'endLine' => 66,
            'startTokenPos' => 46,
            'startFilePos' => 12310,
            'endTokenPos' => 46,
            'endFilePos' => 12331,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 66,
        'endLine' => 66,
        'startColumn' => 5,
        'endColumn' => 74,
      ),
      'COLLECTION_METHOD_SEND_INVOICE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'COLLECTION_METHOD_SEND_INVOICE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'send_invoice\'',
          'attributes' => 
          array (
            'startLine' => 67,
            'endLine' => 67,
            'startTokenPos' => 55,
            'startFilePos' => 12377,
            'endTokenPos' => 55,
            'endFilePos' => 12390,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 67,
        'endLine' => 67,
        'startColumn' => 5,
        'endColumn' => 58,
      ),
      'STATUS_ACTIVE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_ACTIVE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'active\'',
          'attributes' => 
          array (
            'startLine' => 69,
            'endLine' => 69,
            'startTokenPos' => 64,
            'startFilePos' => 12420,
            'endTokenPos' => 64,
            'endFilePos' => 12427,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 69,
        'endLine' => 69,
        'startColumn' => 5,
        'endColumn' => 35,
      ),
      'STATUS_CANCELED' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_CANCELED',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'canceled\'',
          'attributes' => 
          array (
            'startLine' => 70,
            'endLine' => 70,
            'startTokenPos' => 73,
            'startFilePos' => 12458,
            'endTokenPos' => 73,
            'endFilePos' => 12467,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 70,
        'endLine' => 70,
        'startColumn' => 5,
        'endColumn' => 39,
      ),
      'STATUS_INCOMPLETE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_INCOMPLETE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'incomplete\'',
          'attributes' => 
          array (
            'startLine' => 71,
            'endLine' => 71,
            'startTokenPos' => 82,
            'startFilePos' => 12500,
            'endTokenPos' => 82,
            'endFilePos' => 12511,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 71,
        'endLine' => 71,
        'startColumn' => 5,
        'endColumn' => 43,
      ),
      'STATUS_INCOMPLETE_EXPIRED' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_INCOMPLETE_EXPIRED',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'incomplete_expired\'',
          'attributes' => 
          array (
            'startLine' => 72,
            'endLine' => 72,
            'startTokenPos' => 91,
            'startFilePos' => 12552,
            'endTokenPos' => 91,
            'endFilePos' => 12571,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 72,
        'endLine' => 72,
        'startColumn' => 5,
        'endColumn' => 59,
      ),
      'STATUS_PAST_DUE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_PAST_DUE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'past_due\'',
          'attributes' => 
          array (
            'startLine' => 73,
            'endLine' => 73,
            'startTokenPos' => 100,
            'startFilePos' => 12602,
            'endTokenPos' => 100,
            'endFilePos' => 12611,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 73,
        'endLine' => 73,
        'startColumn' => 5,
        'endColumn' => 39,
      ),
      'STATUS_PAUSED' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_PAUSED',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'paused\'',
          'attributes' => 
          array (
            'startLine' => 74,
            'endLine' => 74,
            'startTokenPos' => 109,
            'startFilePos' => 12640,
            'endTokenPos' => 109,
            'endFilePos' => 12647,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 74,
        'endLine' => 74,
        'startColumn' => 5,
        'endColumn' => 35,
      ),
      'STATUS_TRIALING' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_TRIALING',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'trialing\'',
          'attributes' => 
          array (
            'startLine' => 75,
            'endLine' => 75,
            'startTokenPos' => 118,
            'startFilePos' => 12678,
            'endTokenPos' => 118,
            'endFilePos' => 12687,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 75,
        'endLine' => 75,
        'startColumn' => 5,
        'endColumn' => 39,
      ),
      'STATUS_UNPAID' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'STATUS_UNPAID',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'unpaid\'',
          'attributes' => 
          array (
            'startLine' => 76,
            'endLine' => 76,
            'startTokenPos' => 127,
            'startFilePos' => 12716,
            'endTokenPos' => 127,
            'endFilePos' => 12723,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 76,
        'endLine' => 76,
        'startColumn' => 5,
        'endColumn' => 35,
      ),
      'PAYMENT_BEHAVIOR_ALLOW_INCOMPLETE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PAYMENT_BEHAVIOR_ALLOW_INCOMPLETE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'allow_incomplete\'',
          'attributes' => 
          array (
            'startLine' => 250,
            'endLine' => 250,
            'startTokenPos' => 640,
            'startFilePos' => 19993,
            'endTokenPos' => 640,
            'endFilePos' => 20010,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 250,
        'endLine' => 250,
        'startColumn' => 5,
        'endColumn' => 65,
      ),
      'PAYMENT_BEHAVIOR_DEFAULT_INCOMPLETE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PAYMENT_BEHAVIOR_DEFAULT_INCOMPLETE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'default_incomplete\'',
          'attributes' => 
          array (
            'startLine' => 251,
            'endLine' => 251,
            'startTokenPos' => 649,
            'startFilePos' => 20061,
            'endTokenPos' => 649,
            'endFilePos' => 20080,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 251,
        'endLine' => 251,
        'startColumn' => 5,
        'endColumn' => 69,
      ),
      'PAYMENT_BEHAVIOR_ERROR_IF_INCOMPLETE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PAYMENT_BEHAVIOR_ERROR_IF_INCOMPLETE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'error_if_incomplete\'',
          'attributes' => 
          array (
            'startLine' => 252,
            'endLine' => 252,
            'startTokenPos' => 658,
            'startFilePos' => 20132,
            'endTokenPos' => 658,
            'endFilePos' => 20152,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 252,
        'endLine' => 252,
        'startColumn' => 5,
        'endColumn' => 71,
      ),
      'PAYMENT_BEHAVIOR_PENDING_IF_INCOMPLETE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PAYMENT_BEHAVIOR_PENDING_IF_INCOMPLETE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'pending_if_incomplete\'',
          'attributes' => 
          array (
            'startLine' => 253,
            'endLine' => 253,
            'startTokenPos' => 667,
            'startFilePos' => 20206,
            'endTokenPos' => 667,
            'endFilePos' => 20228,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 253,
        'endLine' => 253,
        'startColumn' => 5,
        'endColumn' => 75,
      ),
      'PRORATION_BEHAVIOR_ALWAYS_INVOICE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PRORATION_BEHAVIOR_ALWAYS_INVOICE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'always_invoice\'',
          'attributes' => 
          array (
            'startLine' => 255,
            'endLine' => 255,
            'startTokenPos' => 676,
            'startFilePos' => 20278,
            'endTokenPos' => 676,
            'endFilePos' => 20293,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 255,
        'endLine' => 255,
        'startColumn' => 5,
        'endColumn' => 63,
      ),
      'PRORATION_BEHAVIOR_CREATE_PRORATIONS' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PRORATION_BEHAVIOR_CREATE_PRORATIONS',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'create_prorations\'',
          'attributes' => 
          array (
            'startLine' => 256,
            'endLine' => 256,
            'startTokenPos' => 685,
            'startFilePos' => 20345,
            'endTokenPos' => 685,
            'endFilePos' => 20363,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 256,
        'endLine' => 256,
        'startColumn' => 5,
        'endColumn' => 69,
      ),
      'PRORATION_BEHAVIOR_NONE' => 
      array (
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'name' => 'PRORATION_BEHAVIOR_NONE',
        'modifiers' => 1,
        'type' => NULL,
        'value' => 
        array (
          'code' => '\'none\'',
          'attributes' => 
          array (
            'startLine' => 257,
            'endLine' => 257,
            'startTokenPos' => 694,
            'startFilePos' => 20402,
            'endTokenPos' => 694,
            'endFilePos' => 20407,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 257,
        'endLine' => 257,
        'startColumn' => 5,
        'endColumn' => 43,
      ),
    ),
    'immediateProperties' => 
    array (
    ),
    'immediateMethods' => 
    array (
      'create' => 
      array (
        'name' => 'create',
        'parameters' => 
        array (
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 100,
                'endLine' => 100,
                'startTokenPos' => 144,
                'startFilePos' => 13769,
                'endTokenPos' => 144,
                'endFilePos' => 13772,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 100,
            'endLine' => 100,
            'startColumn' => 35,
            'endColumn' => 48,
            'parameterIndex' => 0,
            'isOptional' => true,
          ),
          'options' => 
          array (
            'name' => 'options',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 100,
                'endLine' => 100,
                'startTokenPos' => 151,
                'startFilePos' => 13786,
                'endTokenPos' => 151,
                'endFilePos' => 13789,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 100,
            'endLine' => 100,
            'startColumn' => 51,
            'endColumn' => 65,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * Creates a new subscription on an existing customer. Each customer can have up to
 * 500 active or scheduled subscriptions.
 *
 * When you create a subscription with
 * <code>collection_method=charge_automatically</code>, the first invoice is
 * finalized as part of the request. The <code>payment_behavior</code> parameter
 * determines the exact behavior of the initial payment.
 *
 * To start subscriptions where the first invoice always begins in a
 * <code>draft</code> status, use <a
 * href="/docs/billing/subscriptions/subscription-schedules#managing">subscription
 * schedules</a> instead. Schedules provide the flexibility to model more complex
 * billing configurations that change over time.
 *
 * @param null|array $params
 * @param null|array|string $options
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Subscription the created resource
 */',
        'startLine' => 100,
        'endLine' => 110,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 17,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'all' => 
      array (
        'name' => 'all',
        'parameters' => 
        array (
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 123,
                'endLine' => 123,
                'startTokenPos' => 248,
                'startFilePos' => 14575,
                'endTokenPos' => 248,
                'endFilePos' => 14578,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 123,
            'endLine' => 123,
            'startColumn' => 32,
            'endColumn' => 45,
            'parameterIndex' => 0,
            'isOptional' => true,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 123,
                'endLine' => 123,
                'startTokenPos' => 255,
                'startFilePos' => 14589,
                'endTokenPos' => 255,
                'endFilePos' => 14592,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 123,
            'endLine' => 123,
            'startColumn' => 48,
            'endColumn' => 59,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * By default, returns a list of subscriptions that have not been canceled. In
 * order to list canceled subscriptions, specify <code>status=canceled</code>.
 *
 * @param null|array $params
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Collection<\\Stripe\\Subscription> of ApiResources
 */',
        'startLine' => 123,
        'endLine' => 128,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 17,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'retrieve' => 
      array (
        'name' => 'retrieve',
        'parameters' => 
        array (
          'id' => 
          array (
            'name' => 'id',
            'default' => NULL,
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 140,
            'endLine' => 140,
            'startColumn' => 37,
            'endColumn' => 39,
            'parameterIndex' => 0,
            'isOptional' => false,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 140,
                'endLine' => 140,
                'startTokenPos' => 311,
                'startFilePos' => 15129,
                'endTokenPos' => 311,
                'endFilePos' => 15132,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 140,
            'endLine' => 140,
            'startColumn' => 42,
            'endColumn' => 53,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * Retrieves the subscription with the given ID.
 *
 * @param array|string $id the ID of the API resource to retrieve, or an options array containing an `id` key
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Subscription
 */',
        'startLine' => 140,
        'endLine' => 147,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 17,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'update' => 
      array (
        'name' => 'update',
        'parameters' => 
        array (
          'id' => 
          array (
            'name' => 'id',
            'default' => NULL,
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 205,
            'endLine' => 205,
            'startColumn' => 35,
            'endColumn' => 37,
            'parameterIndex' => 0,
            'isOptional' => false,
          ),
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 205,
                'endLine' => 205,
                'startTokenPos' => 374,
                'startFilePos' => 18693,
                'endTokenPos' => 374,
                'endFilePos' => 18696,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 205,
            'endLine' => 205,
            'startColumn' => 40,
            'endColumn' => 53,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 205,
                'endLine' => 205,
                'startTokenPos' => 381,
                'startFilePos' => 18707,
                'endTokenPos' => 381,
                'endFilePos' => 18710,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 205,
            'endLine' => 205,
            'startColumn' => 56,
            'endColumn' => 67,
            'parameterIndex' => 2,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * Updates an existing subscription to match the specified parameters. When
 * changing prices or quantities, we optionally prorate the price we charge next
 * month to make up for any price changes. To preview how the proration is
 * calculated, use the <a href="/docs/api/invoices/upcoming">upcoming invoice</a>
 * endpoint.
 *
 * By default, we prorate subscription changes. For example, if a customer signs up
 * on May 1 for a <currency>100</currency> price, they’ll be billed
 * <currency>100</currency> immediately. If on May 15 they switch to a
 * <currency>200</currency> price, then on June 1 they’ll be billed
 * <currency>250</currency> (<currency>200</currency> for a renewal of her
 * subscription, plus a <currency>50</currency> prorating adjustment for half of
 * the previous month’s <currency>100</currency> difference). Similarly, a
 * downgrade generates a credit that is applied to the next invoice. We also
 * prorate when you make quantity changes.
 *
 * Switching prices does not normally change the billing date or generate an
 * immediate charge unless:
 *
 * <ul> <li>The billing interval is changed (for example, from monthly to
 * yearly).</li> <li>The subscription moves from free to paid, or paid to
 * free.</li> <li>A trial starts or ends.</li> </ul>
 *
 * In these cases, we apply a credit for the unused time on the previous price,
 * immediately charge the customer using the new price, and reset the billing date.
 *
 * If you want to charge for an upgrade immediately, pass
 * <code>proration_behavior</code> as <code>always_invoice</code> to create
 * prorations, automatically invoice the customer for those proration adjustments,
 * and attempt to collect payment. If you pass <code>create_prorations</code>, the
 * prorations are created but not automatically invoiced. If you want to bill the
 * customer for the prorations before the subscription’s renewal date, you need to
 * manually <a href="/docs/api/invoices/create">invoice the customer</a>.
 *
 * If you don’t want to prorate, set the <code>proration_behavior</code> option to
 * <code>none</code>. With this option, the customer is billed
 * <currency>100</currency> on May 1 and <currency>200</currency> on June 1.
 * Similarly, if you set <code>proration_behavior</code> to <code>none</code> when
 * switching between different billing intervals (for example, from monthly to
 * yearly), we don’t generate any credits for the old subscription’s unused time.
 * We still reset the billing date and bill immediately for the new subscription.
 *
 * Updating the quantity on a subscription many times in an hour may result in <a
 * href="/docs/rate-limits">rate limiting</a>. If you need to bill for a frequently
 * changing quantity, consider integrating <a
 * href="/docs/billing/subscriptions/usage-based">usage-based billing</a> instead.
 *
 * @param string $id the ID of the resource to update
 * @param null|array $params
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Subscription the updated resource
 */',
        'startLine' => 205,
        'endLine' => 215,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 17,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'getSavedNestedResources' => 
      array (
        'name' => 'getSavedNestedResources',
        'parameters' => 
        array (
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => NULL,
        'startLine' => 221,
        'endLine' => 231,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 17,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'deleteDiscount' => 
      array (
        'name' => 'deleteDiscount',
        'parameters' => 
        array (
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 241,
                'endLine' => 241,
                'startTokenPos' => 553,
                'startFilePos' => 19695,
                'endTokenPos' => 553,
                'endFilePos' => 19698,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 241,
            'endLine' => 241,
            'startColumn' => 36,
            'endColumn' => 49,
            'parameterIndex' => 0,
            'isOptional' => true,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 241,
                'endLine' => 241,
                'startTokenPos' => 560,
                'startFilePos' => 19709,
                'endTokenPos' => 560,
                'endFilePos' => 19712,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 241,
            'endLine' => 241,
            'startColumn' => 52,
            'endColumn' => 63,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * @param null|array $params
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Subscription the updated subscription
 */',
        'startLine' => 241,
        'endLine' => 248,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 1,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'cancel' => 
      array (
        'name' => 'cancel',
        'parameters' => 
        array (
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 267,
                'endLine' => 267,
                'startTokenPos' => 709,
                'startFilePos' => 20683,
                'endTokenPos' => 709,
                'endFilePos' => 20686,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 267,
            'endLine' => 267,
            'startColumn' => 28,
            'endColumn' => 41,
            'parameterIndex' => 0,
            'isOptional' => true,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 267,
                'endLine' => 267,
                'startTokenPos' => 716,
                'startFilePos' => 20697,
                'endTokenPos' => 716,
                'endFilePos' => 20700,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 267,
            'endLine' => 267,
            'startColumn' => 44,
            'endColumn' => 55,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * @param null|array $params
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Subscription the canceled subscription
 */',
        'startLine' => 267,
        'endLine' => 274,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 1,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'resume' => 
      array (
        'name' => 'resume',
        'parameters' => 
        array (
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 284,
                'endLine' => 284,
                'startTokenPos' => 789,
                'startFilePos' => 21175,
                'endTokenPos' => 789,
                'endFilePos' => 21178,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 284,
            'endLine' => 284,
            'startColumn' => 28,
            'endColumn' => 41,
            'parameterIndex' => 0,
            'isOptional' => true,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 284,
                'endLine' => 284,
                'startTokenPos' => 796,
                'startFilePos' => 21189,
                'endTokenPos' => 796,
                'endFilePos' => 21192,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 284,
            'endLine' => 284,
            'startColumn' => 44,
            'endColumn' => 55,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * @param null|array $params
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\Subscription the resumed subscription
 */',
        'startLine' => 284,
        'endLine' => 291,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 1,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
      'search' => 
      array (
        'name' => 'search',
        'parameters' => 
        array (
          'params' => 
          array (
            'name' => 'params',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 301,
                'endLine' => 301,
                'startTokenPos' => 875,
                'startFilePos' => 21713,
                'endTokenPos' => 875,
                'endFilePos' => 21716,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 301,
            'endLine' => 301,
            'startColumn' => 35,
            'endColumn' => 48,
            'parameterIndex' => 0,
            'isOptional' => true,
          ),
          'opts' => 
          array (
            'name' => 'opts',
            'default' => 
            array (
              'code' => 'null',
              'attributes' => 
              array (
                'startLine' => 301,
                'endLine' => 301,
                'startTokenPos' => 882,
                'startFilePos' => 21727,
                'endTokenPos' => 882,
                'endFilePos' => 21730,
              ),
            ),
            'type' => NULL,
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 301,
            'endLine' => 301,
            'startColumn' => 51,
            'endColumn' => 62,
            'parameterIndex' => 1,
            'isOptional' => true,
          ),
        ),
        'returnsReference' => false,
        'returnType' => NULL,
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * @param null|array $params
 * @param null|array|string $opts
 *
 * @throws \\Stripe\\Exception\\ApiErrorException if the request fails
 *
 * @return \\Stripe\\SearchResult<\\Stripe\\Subscription> the subscription search results
 */',
        'startLine' => 301,
        'endLine' => 306,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 17,
        'namespace' => 'Stripe',
        'declaringClassName' => 'Stripe\\Subscription',
        'implementingClassName' => 'Stripe\\Subscription',
        'currentClassName' => 'Stripe\\Subscription',
        'aliasName' => NULL,
      ),
    ),
    'traitsData' => 
    array (
      'aliases' => 
      array (
        'Stripe\\ApiOperations\\Delete' => 
        array (
          0 => 
          array (
            'alias' => '_delete',
            'method' => 'delete',
            'hash' => 'stripe\\apioperations\\delete::delete',
          ),
        ),
      ),
      'modifiers' => 
      array (
        'stripe\\apioperations\\delete::delete' => 2,
      ),
      'precedences' => 
      array (
      ),
      'hashes' => 
      array (
        'stripe\\apioperations\\delete::delete' => 'Stripe\\ApiOperations\\Delete::delete',
      ),
    ),
  ),
));