#!/bin/bash
set -e

CONFIG="/var/www/html/ipconfig.php"

# Validate required environment variables
: "${IP_URL:?IP_URL is required (e.g. https://invoices.example.com)}"
: "${DB_HOSTNAME:?DB_HOSTNAME is required}"
: "${DB_USERNAME:?DB_USERNAME is required}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"
: "${DB_DATABASE:?DB_DATABASE is required}"
: "${ENCRYPTION_KEY:?ENCRYPTION_KEY is required — generate with: openssl rand -base64 32}"

# Generate ipconfig.php from environment variables
cat > "$CONFIG" <<EOF
# <?php exit('No direct script access allowed'); ?>
# InvoicePlane Configuration File — generated by entrypoint.sh

IP_URL=${IP_URL}

ENABLE_DEBUG=${ENABLE_DEBUG:-false}
CI_ENV=${CI_ENV:-production}

X_FRAME_OPTIONS=${X_FRAME_OPTIONS:-SAMEORIGIN}
ENABLE_X_CONTENT_TYPE_OPTIONS=${ENABLE_X_CONTENT_TYPE_OPTIONS:-true}
SESS_REGENERATE_DESTROY=${SESS_REGENERATE_DESTROY:-false}

DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-english}

DISABLE_SETUP=true
REMOVE_INDEXPHP=true

DB_HOSTNAME=${DB_HOSTNAME}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=${DB_DATABASE}
DB_PORT=${DB_PORT:-3306}

CUSTOM_TEMPLATES_FOLDER=${CUSTOM_TEMPLATES_FOLDER:-/var/www/html/templates/}

SESS_EXPIRATION=${SESS_EXPIRATION:-864000}
SESS_MATCH_IP=${SESS_MATCH_IP:-true}

LEGACY_CALCULATION=${LEGACY_CALCULATION:-false}

ENABLE_INVOICE_DELETION=${ENABLE_INVOICE_DELETION:-false}
DISABLE_READ_ONLY=${DISABLE_READ_ONLY:-false}

PASSWORD_RESET_IP_MAX_ATTEMPTS=${PASSWORD_RESET_IP_MAX_ATTEMPTS:-5}
PASSWORD_RESET_IP_WINDOW_MINUTES=${PASSWORD_RESET_IP_WINDOW_MINUTES:-60}
PASSWORD_RESET_EMAIL_MAX_ATTEMPTS=${PASSWORD_RESET_EMAIL_MAX_ATTEMPTS:-3}
PASSWORD_RESET_EMAIL_WINDOW_HOURS=${PASSWORD_RESET_EMAIL_WINDOW_HOURS:-1}

SUMEX_SETTINGS=${SUMEX_SETTINGS:-false}
SUMEX_URL=${SUMEX_URL:-}

ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENCRYPTION_CIPHER=${ENCRYPTION_CIPHER:-AES-256}

SETUP_COMPLETED=true
EOF

# Protect the custom templates directory from direct HTTP access.
if [ -n "${CUSTOM_TEMPLATES_FOLDER:-}" ]; then
    mkdir -p "$CUSTOM_TEMPLATES_FOLDER"
    if [ ! -f "$CUSTOM_TEMPLATES_FOLDER/.htaccess" ]; then
        echo "Deny from all" > "$CUSTOM_TEMPLATES_FOLDER/.htaccess"
    fi
fi

cd /var/www/html && php index.php setup/cli/migrate
php index.php setup/cli/create_default_user

exec "$@"
