#!/bin/bash
set -e

CONFIG="/var/www/html/ipconfig.php"

# Reject configuration values that contain newline or carriage return characters.
# Such characters could allow an attacker to inject extra lines into ipconfig.php
# (e.g. to override DISABLE_SETUP=false), so we fail fast rather than silently strip.
sanitize_config_value() {
    local value="$1"
    case "$value" in
        *$'\n'* | *$'\r'*)
            echo "Error: configuration value must not contain newline or carriage-return characters." >&2
            exit 1
            ;;
    esac
    printf '%s' "$value"
}

# Validate required environment variables
: "${IP_URL:?IP_URL is required (e.g. https://invoices.example.com)}"
: "${DB_HOSTNAME:?DB_HOSTNAME is required}"
: "${DB_USERNAME:?DB_USERNAME is required}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"
: "${DB_DATABASE:?DB_DATABASE is required}"
: "${ENCRYPTION_KEY:?ENCRYPTION_KEY is required — generate with: openssl rand -base64 32}"

IP_URL_SAFE="$(sanitize_config_value "$IP_URL")"
ENABLE_DEBUG_SAFE="$(sanitize_config_value "${ENABLE_DEBUG:-false}")"
CI_ENV_SAFE="$(sanitize_config_value "${CI_ENV:-production}")"
X_FRAME_OPTIONS_SAFE="$(sanitize_config_value "${X_FRAME_OPTIONS:-SAMEORIGIN}")"
ENABLE_X_CONTENT_TYPE_OPTIONS_SAFE="$(sanitize_config_value "${ENABLE_X_CONTENT_TYPE_OPTIONS:-true}")"
SESS_REGENERATE_DESTROY_SAFE="$(sanitize_config_value "${SESS_REGENERATE_DESTROY:-false}")"
DEFAULT_LANGUAGE_SAFE="$(sanitize_config_value "${DEFAULT_LANGUAGE:-english}")"
DB_HOSTNAME_SAFE="$(sanitize_config_value "$DB_HOSTNAME")"
DB_USERNAME_SAFE="$(sanitize_config_value "$DB_USERNAME")"
DB_PASSWORD_SAFE="$(sanitize_config_value "$DB_PASSWORD")"
DB_DATABASE_SAFE="$(sanitize_config_value "$DB_DATABASE")"
DB_PORT_SAFE="$(sanitize_config_value "${DB_PORT:-3306}")"
CUSTOM_TEMPLATES_FOLDER_SAFE="$(sanitize_config_value "${CUSTOM_TEMPLATES_FOLDER:-/var/www/html/templates/}")"
CUSTOM_INVOICE_TEMPLATES_PDF_SAFE="$(sanitize_config_value "${CUSTOM_INVOICE_TEMPLATES_PDF:-}")"
CUSTOM_INVOICE_TEMPLATES_PUBLIC_SAFE="$(sanitize_config_value "${CUSTOM_INVOICE_TEMPLATES_PUBLIC:-}")"
CUSTOM_QUOTE_TEMPLATES_PDF_SAFE="$(sanitize_config_value "${CUSTOM_QUOTE_TEMPLATES_PDF:-}")"
CUSTOM_QUOTE_TEMPLATES_PUBLIC_SAFE="$(sanitize_config_value "${CUSTOM_QUOTE_TEMPLATES_PUBLIC:-}")"
SESS_EXPIRATION_SAFE="$(sanitize_config_value "${SESS_EXPIRATION:-864000}")"
SESS_MATCH_IP_SAFE="$(sanitize_config_value "${SESS_MATCH_IP:-true}")"
LEGACY_CALCULATION_SAFE="$(sanitize_config_value "${LEGACY_CALCULATION:-false}")"
ENABLE_INVOICE_DELETION_SAFE="$(sanitize_config_value "${ENABLE_INVOICE_DELETION:-false}")"
DISABLE_READ_ONLY_SAFE="$(sanitize_config_value "${DISABLE_READ_ONLY:-false}")"
PASSWORD_RESET_IP_MAX_ATTEMPTS_SAFE="$(sanitize_config_value "${PASSWORD_RESET_IP_MAX_ATTEMPTS:-5}")"
PASSWORD_RESET_IP_WINDOW_MINUTES_SAFE="$(sanitize_config_value "${PASSWORD_RESET_IP_WINDOW_MINUTES:-60}")"
PASSWORD_RESET_EMAIL_MAX_ATTEMPTS_SAFE="$(sanitize_config_value "${PASSWORD_RESET_EMAIL_MAX_ATTEMPTS:-3}")"
PASSWORD_RESET_EMAIL_WINDOW_HOURS_SAFE="$(sanitize_config_value "${PASSWORD_RESET_EMAIL_WINDOW_HOURS:-1}")"
SUMEX_SETTINGS_SAFE="$(sanitize_config_value "${SUMEX_SETTINGS:-false}")"
SUMEX_URL_SAFE="$(sanitize_config_value "${SUMEX_URL:-}")"
ENCRYPTION_KEY_SAFE="$(sanitize_config_value "$ENCRYPTION_KEY")"
ENCRYPTION_CIPHER_SAFE="$(sanitize_config_value "${ENCRYPTION_CIPHER:-AES-256}")"

# Generate ipconfig.php from sanitized environment variables
cat > "$CONFIG" <<EOF
# <?php exit('No direct script access allowed'); ?>
# InvoicePlane Configuration File — generated by entrypoint.sh

IP_URL=${IP_URL_SAFE}

ENABLE_DEBUG=${ENABLE_DEBUG_SAFE}
CI_ENV=${CI_ENV_SAFE}

X_FRAME_OPTIONS=${X_FRAME_OPTIONS_SAFE}
ENABLE_X_CONTENT_TYPE_OPTIONS=${ENABLE_X_CONTENT_TYPE_OPTIONS_SAFE}
SESS_REGENERATE_DESTROY=${SESS_REGENERATE_DESTROY_SAFE}

DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE_SAFE}

DISABLE_SETUP=true
REMOVE_INDEXPHP=true

DB_HOSTNAME=${DB_HOSTNAME_SAFE}
DB_USERNAME=${DB_USERNAME_SAFE}
DB_PASSWORD=${DB_PASSWORD_SAFE}
DB_DATABASE=${DB_DATABASE_SAFE}
DB_PORT=${DB_PORT_SAFE}

CUSTOM_TEMPLATES_FOLDER=${CUSTOM_TEMPLATES_FOLDER_SAFE}
CUSTOM_INVOICE_TEMPLATES_PDF=${CUSTOM_INVOICE_TEMPLATES_PDF_SAFE}
CUSTOM_INVOICE_TEMPLATES_PUBLIC=${CUSTOM_INVOICE_TEMPLATES_PUBLIC_SAFE}
CUSTOM_QUOTE_TEMPLATES_PDF=${CUSTOM_QUOTE_TEMPLATES_PDF_SAFE}
CUSTOM_QUOTE_TEMPLATES_PUBLIC=${CUSTOM_QUOTE_TEMPLATES_PUBLIC_SAFE}

SESS_EXPIRATION=${SESS_EXPIRATION_SAFE}
SESS_MATCH_IP=${SESS_MATCH_IP_SAFE}

LEGACY_CALCULATION=${LEGACY_CALCULATION_SAFE}

ENABLE_INVOICE_DELETION=${ENABLE_INVOICE_DELETION_SAFE}
DISABLE_READ_ONLY=${DISABLE_READ_ONLY_SAFE}

PASSWORD_RESET_IP_MAX_ATTEMPTS=${PASSWORD_RESET_IP_MAX_ATTEMPTS_SAFE}
PASSWORD_RESET_IP_WINDOW_MINUTES=${PASSWORD_RESET_IP_WINDOW_MINUTES_SAFE}
PASSWORD_RESET_EMAIL_MAX_ATTEMPTS=${PASSWORD_RESET_EMAIL_MAX_ATTEMPTS_SAFE}
PASSWORD_RESET_EMAIL_WINDOW_HOURS=${PASSWORD_RESET_EMAIL_WINDOW_HOURS_SAFE}

SUMEX_SETTINGS=${SUMEX_SETTINGS_SAFE}
SUMEX_URL=${SUMEX_URL_SAFE}

ENCRYPTION_KEY=${ENCRYPTION_KEY_SAFE}
ENCRYPTION_CIPHER=${ENCRYPTION_CIPHER_SAFE}

SETUP_COMPLETED=true
EOF

# Protect the custom templates directory from direct HTTP access.
if [ -n "${CUSTOM_TEMPLATES_FOLDER:-}" ]; then
    mkdir -p "$CUSTOM_TEMPLATES_FOLDER"
    if [ ! -f "$CUSTOM_TEMPLATES_FOLDER/.htaccess" ]; then
        echo "Deny from all" > "$CUSTOM_TEMPLATES_FOLDER/.htaccess"
    fi
fi

cd /var/www/html && php public/index.php setup/cli/migrate
php public/index.php setup/cli/create_default_user

exec "$@"
