name: Bug Report
description: Report a problem with InvoicePlane.
labels: ["bug"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Provide a short, descriptive summary of the issue.
      placeholder: "Brief summary of the bug"

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen under normal circumstances?
      placeholder: "Describe the expected result"

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: What actually happens instead of the expected behavior?
      placeholder: "Explain the current result"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: Attach relevant screenshots if applicable.
      render: textarea

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution (Optional)
      description: Suggest a potential fix if you have one.

  - type: textarea
    id: context
    attributes:
      label: Context (Environment)
      description: Describe the context (OS, InvoicePlane version, etc.) where the issue occurs.

  - type: textarea
    id: failure_logs
    attributes:
      label: Failure Logs (Optional)
      description: Include any relevant logs or pastebin links.
