name: Feature Request
description: Suggest a new feature or improvement for InvoicePlane.
labels: ["enhancement"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Provide a short, descriptive summary of the feature.
      placeholder: "Brief summary of the feature"

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature or improvement.
      placeholder: "Explain what this feature does and why it's needed."

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Provide examples of how this feature will be used.
      placeholder: "Describe the specific scenarios where this feature would be beneficial."

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Include any additional information or context to support the request.

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      options:
        - Low
        - Medium
        - High
