<?php

/**
 * InvoicePlane public front controller.
 *
 * This directory (public/) is the web server document root. All application
 * code, configuration and writable storage live one level up, outside the
 * document root, and are reached through IP_ROOTPATH.
 *
 * DO NOT EDIT THIS FILE!
 * Make a copy of the ipconfig.php.example file, rename the copy to
 * 'ipconfig.php' and set your settings in that file.
 */

// The project root — one level above this document root.
define('IP_ROOTPATH', dirname(__DIR__));

// This document root (used for the FCPATH constant).
define('IP_WEBROOT', __DIR__);

require IP_ROOTPATH . DIRECTORY_SEPARATOR . 'kernel.php';
