<?php

declare(strict_types=1);

/**
 * Lightweight, dependency-free assertion audit for PHPUnit test methods.
 *
 * This intentionally reports rather than rewrites tests. It catches the
 * common false-positive shapes (status-only, HTML-shell-only, generic redirect
 * and database-presence-only) while leaving domain-specific judgment to the
 * test author.
 */
final class AssertionQualityInventory
{
    /** @return array<int, array<string, mixed>> */
    public static function build(string $root): array
    {
        $inventory = [];
        $files     = [];
        foreach (['Unit', 'Feature', 'Integration', 'Scripts'] as $suite) {
            $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(
                $root . '/tests/' . $suite,
                FilesystemIterator::SKIP_DOTS,
            ));
            foreach ($iterator as $file) {
                if ($file instanceof SplFileInfo && $file->isFile() && $file->getExtension() === 'php') {
                    $files[] = $file->getPathname();
                }
            }
        }
        sort($files);

        foreach ($files as $file) {
            $source = (string) file_get_contents($file);
            preg_match_all('/#\[Test\][\s\S]*?public function\s+(\w+)\s*\([^)]*\)[^{]*\{/', $source, $matches, PREG_OFFSET_CAPTURE);
            foreach ($matches[1] as [$method, $offset]) {
                $start = (int) $offset + strlen($method);
                $body  = self::methodBody($source, strpos($source, '{', $start));
                preg_match_all('/(?:assert|expect)[A-Z]\w*\s*\(/', $body, $assertions);
                $names = array_values(array_unique(array_map(
                    static fn (string $assertion): string => (string) preg_replace('/\s*\($/', '', $assertion),
                    $assertions[0],
                )));
                $meaningful = array_values(array_filter($names, static fn (string $name): bool => ! preg_match(
                    '/assert(?:Same|Status|True|GreaterThan|LessThan|StringContainsString|StringNotContainsString|NotEmpty|NotNull|ArrayHasKey|FileExists|DatabaseHas)\b/',
                    $name,
                )));
                $shape       = self::shape($names, $meaningful);
                $inventory[] = [
                    'file'       => substr($file, strlen($root) + 1),
                    'method'     => $method,
                    'category'   => self::category($file),
                    'assertions' => $names,
                    'shape'      => $shape,
                    'status'     => $shape === 'healthy' ? 'pass' : 'review',
                ];
            }
        }

        return $inventory;
    }

    /** @param array<int, array<string, mixed>> $inventory */
    public static function toMarkdown(array $inventory): string
    {
        $counts = array_count_values(array_column($inventory, 'shape'));
        $lines  = ['# Assertion-quality inventory', '', 'Generated by `php tests/Support/generate-assertion-quality-inventory.php`.', '', '| Shape | Tests |', '| --- | ---: |'];
        foreach ($counts as $shape => $count) {
            $lines[] = '| ' . $shape . ' | ' . $count . ' |';
        }
        $lines[] = '';
        $lines[] = '## Review findings';
        $lines[] = '';
        $lines[] = '| File | Test | Category | Shape | Assertions |';
        $lines[] = '| --- | --- | --- | --- | --- |';
        foreach ($inventory as $item) {
            if ($item['status'] === 'pass') {
                continue;
            }
            $lines[] = '| `' . $item['file'] . '` | `' . $item['method'] . '` | ' . $item['category'] . ' | ' . $item['shape'] . ' | ' . implode(', ', $item['assertions']) . ' |';
        }

        return implode("\n", $lines) . "\n";
    }

    /** @param array<int, string> $assertions @param array<int, string> $meaningful */
    private static function shape(array $assertions, array $meaningful): string
    {
        if ($assertions === []) {
            return 'no-assertions';
        }
        if ($meaningful !== []) {
            return 'healthy';
        }
        $text = implode(' ', $assertions);
        if (preg_match('/assert(?:Status|Same)\b/', $text)) {
            return 'status-only';
        }
        if (preg_match('/assert(?:StringContainsString|StringNotContainsString)\b/', $text)) {
            return 'generic-body-only';
        }
        if (preg_match('/assert(?:True|Redirect)\b/', $text)) {
            return 'generic-redirect-only';
        }
        if (preg_match('/assert(?:DatabaseHas|NotNull)\b/', $text)) {
            return 'database-presence-only';
        }

        return 'review';
    }

    private static function category(string $file): string
    {
        foreach (['Security', 'Invoices', 'Payments', 'Products', 'Projects', 'Quotes', 'Clients', 'Users'] as $category) {
            if (preg_match('#/tests/(?:Feature|Integration)/' . preg_quote($category, '#') . '/#', $file)) {
                return strtolower($category);
            }
        }
        if (str_contains($file, '/Unit/')) {
            return 'unit';
        }
        if (str_contains($file, '/Integration/')) {
            return 'external-integration';
        }

        return 'core';
    }

    private static function methodBody(string $source, int|false $opening): string
    {
        if ($opening === false) {
            return '';
        }
        $depth  = 0;
        $length = strlen($source);
        for ($i = $opening; $i < $length; $i++) {
            if ($source[$i] === '{') {
                $depth++;
            }
            if ($source[$i] === '}' && --$depth === 0) {
                return substr($source, $opening + 1, $i - $opening - 1);
            }
        }

        return substr($source, $opening + 1);
    }
}
