<?php

declare(strict_types=1);

final class ClassCoverageInventory
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public static function build(string $repoRoot): array
    {
        $classes = [];

        foreach (self::sourceFiles($repoRoot) as $file) {
            $relative = self::relativePath($repoRoot, $file);
            $class    = self::classInfo($file);

            if ($class === null) {
                continue;
            }

            $classes[] = [
                'class'          => $class['class'],
                'path'           => $relative,
                'module'         => self::moduleFor($relative),
                'kind'           => self::kindFor($relative),
                'public_methods' => $class['public_methods'],
                'risk'           => self::riskFor($relative, $class['class'], $class['public_methods']),
                'tests'          => self::testsFor($repoRoot, $class['class'], $relative),
            ];
        }

        usort(
            $classes,
            static fn (array $a, array $b): int => [$a['module'], $a['kind'], $a['class']]
                <=> [$b['module'], $b['kind'], $b['class']]
        );

        return $classes;
    }

    /**
     * @param array<int, array<string, mixed>> $classes
     */
    public static function toMarkdown(array $classes): string
    {
        $lines = [
            '# Testable Class Coverage Inventory',
            '',
            'Generated by `php tests/Support/generate-class-coverage-inventory.php`.',
            '',
            '- Scope: `application/modules/*/{controllers,models,libraries}` and `application/libraries`',
            '- Status meanings: `covered`, `partial`, `missing`.',
            '',
        ];

        $summary = self::summary($classes);
        $lines[] = '## Summary';
        $lines[] = '';
        $lines[] = '| Status | Classes |';
        $lines[] = '| --- | ---: |';
        foreach (['covered', 'partial', 'missing'] as $status) {
            $lines[] = '| ' . $status . ' | ' . ($summary[$status] ?? 0) . ' |';
        }
        $lines[] = '';

        $lines[] = '## Inventory';
        $lines[] = '';
        $lines[] = '| Module | Kind | Risk | Status | Class | Public Methods | Tests | Source |';
        $lines[] = '| --- | --- | --- | --- | --- | ---: | --- | --- |';

        foreach ($classes as $class) {
            $tests   = $class['tests'];
            $status  = self::statusForTests($tests);
            $lines[] = sprintf(
                '| %s | %s | %s | %s | `%s` | %d | %s | `%s` |',
                self::escape((string) $class['module']),
                self::escape((string) $class['kind']),
                self::escape((string) $class['risk']),
                $status,
                self::escape((string) $class['class']),
                count($class['public_methods']),
                $tests === [] ? '—' : implode('<br>', array_map(static fn (string $test): string => '`' . self::escape($test) . '`', $tests)),
                self::escape((string) $class['path'])
            );
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @return array<string, int>
     */
    private static function summary(array $classes): array
    {
        $summary = ['covered' => 0, 'partial' => 0, 'missing' => 0];

        foreach ($classes as $class) {
            $summary[self::statusForTests($class['tests'])]++;
        }

        return $summary;
    }

    /**
     * @param array<int, string> $tests
     */
    private static function statusForTests(array $tests): string
    {
        if ($tests === []) {
            return 'missing';
        }

        return count($tests) === 1 ? 'partial' : 'covered';
    }

    /**
     * @return array<int, string>
     */
    private static function sourceFiles(string $repoRoot): array
    {
        $files = [];

        foreach (glob($repoRoot . '/application/modules/*') ?: [] as $modulePath) {
            if ( ! is_dir($modulePath)) {
                continue;
            }

            foreach (['controllers', 'models', 'libraries'] as $kind) {
                $path = $modulePath . '/' . $kind;
                if (is_dir($path)) {
                    foreach (self::phpFilesIn($path) as $file) {
                        $files[$file] = $file;
                    }
                }
            }
        }

        foreach (self::phpFilesIn($repoRoot . '/application/libraries', false) as $file) {
            $files[$file] = $file;
        }

        sort($files);

        return array_values($files);
    }

    /**
     * @return array<int, string>
     */
    private static function phpFilesIn(string $path, bool $recursive = true): array
    {
        if ( ! is_dir($path)) {
            return [];
        }

        $files = [];

        if ($recursive) {
            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS)
            );

            foreach ($iterator as $file) {
                if ($file instanceof SplFileInfo && $file->isFile() && $file->getExtension() === 'php') {
                    $files[] = $file->getPathname();
                }
            }
        } else {
            foreach (glob($path . '/*.php') ?: [] as $file) {
                $files[] = $file;
            }
        }

        sort($files);

        return array_values($files);
    }

    /**
     * @return array{class: string, public_methods: array<int, string>}|null
     */
    private static function classInfo(string $file): ?array
    {
        $tokens        = token_get_all((string) file_get_contents($file));
        $class         = null;
        $publicMethods = [];
        $visibility    = null;

        for ($i = 0, $count = count($tokens); $i < $count; $i++) {
            $token = $tokens[$i];
            if ( ! is_array($token)) {
                continue;
            }

            if ($token[0] === T_CLASS) {
                $class = self::nextDeclarationString($tokens, $i + 1);
                continue;
            }

            if (in_array($token[0], [T_PUBLIC, T_PROTECTED, T_PRIVATE], true)) {
                $visibility = $token[0];
                continue;
            }

            if ($token[0] === T_FUNCTION && $visibility === T_PUBLIC) {
                $method = self::nextDeclarationString($tokens, $i + 1);
                if ($method !== null && ! str_starts_with($method, '__')) {
                    $publicMethods[] = $method;
                }
                $visibility = null;
            }
        }

        if ($class === null) {
            return null;
        }

        sort($publicMethods);

        return ['class' => $class, 'public_methods' => array_values(array_unique($publicMethods))];
    }

    /**
     * @param array<int, mixed> $tokens
     */
    private static function nextDeclarationString(array $tokens, int $offset): ?string
    {
        for ($i = $offset, $count = count($tokens); $i < $count; $i++) {
            $token = $tokens[$i];
            if (is_array($token) && in_array($token[0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true)) {
                continue;
            }

            if (is_array($token) && $token[0] === T_STRING) {
                return $token[1];
            }

            return null;
        }

        return null;
    }

    private static function moduleFor(string $relative): string
    {
        if (preg_match('#^application/modules/([^/]+)/#', $relative, $matches)) {
            return $matches[1];
        }

        return 'application';
    }

    private static function kindFor(string $relative): string
    {
        if (str_contains($relative, '/controllers/')) {
            return 'controller';
        }

        if (str_contains($relative, '/models/')) {
            return 'model';
        }

        if (str_contains($relative, '/libraries/') || str_starts_with($relative, 'application/libraries/')) {
            return 'library';
        }

        return 'library';
    }

    /**
     * @param array<int, string> $methods
     */
    private static function riskFor(string $relative, string $class, array $methods): string
    {
        $haystack = strtolower($relative . ' ' . $class . ' ' . implode(' ', $methods));

        if (str_contains($haystack, 'security') || str_contains($haystack, 'crypt') || str_contains($haystack, 'csrf')) {
            return 'security';
        }

        if (preg_match('/delete|save|insert|update|payment|invoice|quote|tax|amount|gateway|sync|send/', $haystack) === 1) {
            return 'money-or-mutation';
        }

        if (str_contains($haystack, 'integration') || str_contains($haystack, 'peppol') || str_contains($haystack, 'provider')) {
            return 'integration';
        }

        return 'standard';
    }

    /**
     * @return array<int, string>
     */
    private static function testsFor(string $repoRoot, string $class, string $sourcePath): array
    {
        $candidates = [];
        $classStem  = preg_replace('/^Mdl_/', '', $class) ?: $class;
        $classWords = strtolower((string) preg_replace('/[^a-z0-9]+/i', '', $classStem));
        $sourceStem = strtolower((string) preg_replace('/[^a-z0-9]+/i', '', basename($sourcePath, '.php')));
        $kind       = self::kindFor($sourcePath);
        $routeStem  = strtolower(basename($sourcePath, '.php'));
        $module     = strtolower(self::moduleFor($sourcePath));

        foreach (self::testFiles($repoRoot) as $test) {
            $relative = self::relativePath($repoRoot, $test);
            $content  = (string) file_get_contents($test);
            $testStem = strtolower((string) preg_replace('/[^a-z0-9]+/i', '', basename($test, '.php')));

            // Controllers are credited purely on route evidence: an HTTP call
            // whose URI's first segment is this class's own module and whose
            // remaining segments include this class's own route stem. That is
            // precise enough on its own — CI3/HMVC's router resolves the first
            // URI segment as the module directory (MX/Router.php locate()), so
            // this also rules out cross-module name collisions (e.g. a test
            // hitting the admin `/invoices` listing must not credit the
            // differently-routed `guest/controllers/Invoices.php`). A bare
            // name/filename match is neither necessary nor sufficient here.
            if ($kind === 'controller') {
                if (self::exercisesRoute($content, $module, $routeStem)) {
                    $candidates[] = $relative;
                }

                continue;
            }

            $textMatch = self::containsClassReference($content, $class)
                || (strlen($classWords) >= 5 && str_contains($testStem, $classWords))
                || (strlen($sourceStem) >= 5 && str_contains($testStem, $sourceStem));

            if ($textMatch) {
                $candidates[] = $relative;
            }
        }

        sort($candidates);

        return array_values(array_unique($candidates));
    }

    private static function containsClassReference(string $content, string $class): bool
    {
        if (strlen($class) < 6) {
            return false;
        }

        return preg_match('/(?<![A-Za-z0-9_])' . preg_quote($class, '/') . '(?![A-Za-z0-9_])/', $content) === 1;
    }

    private static function exercisesRoute(string $content, string $module, string $routeStem): bool
    {
        if ($routeStem === '') {
            return true;
        }

        $uris = [];

        if (preg_match_all('/->(?:get|post|delete)\(\s*[\'"]([^\'"]*)[\'"]/', $content, $matches) > 0) {
            $uris = array_merge($uris, $matches[1]);
        }

        // ->ajax('METHOD', $uri, ...) and ->request('METHOD', $uri, ...) share the
        // same (method, uri) call shape.
        if (preg_match_all('/->(?:ajax|request)\(\s*[\'"][A-Za-z]+[\'"]\s*,\s*[\'"]([^\'"]*)[\'"]/', $content, $ajaxMatches) > 0) {
            $uris = array_merge($uris, $ajaxMatches[1]);
        }

        foreach ($uris as $uri) {
            $segments = array_values(array_filter(explode('/', strtolower($uri))));

            // HMVC resolves the first URI segment as the module directory
            // (MX/Router.php locate()), so it must match before the remaining
            // segments are trusted to name a controller within that module.
            if ($segments === [] || $segments[0] !== $module) {
                continue;
            }

            if (in_array($routeStem, $segments, true)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return array<int, string>
     */
    private static function testFiles(string $repoRoot): array
    {
        $files = [];

        foreach (['Feature', 'Unit'] as $suite) {
            foreach (self::phpFilesIn($repoRoot . '/tests/' . $suite) as $file) {
                if (str_ends_with($file, 'Test.php')) {
                    $files[] = $file;
                }
            }
        }

        sort($files);

        return $files;
    }

    private static function relativePath(string $repoRoot, string $path): string
    {
        return ltrim(str_replace($repoRoot, '', $path), '/');
    }

    private static function escape(string $value): string
    {
        return str_replace('|', '\\|', $value);
    }
}
