name: Build & Push MariaDB Docker Image

on:
  push:
    branches:
      - development
    paths:
      - 'resources/docker/mariadb/Dockerfile'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build MariaDB Image
        run: |
          docker build -t mariadb-test ./resources/docker/mariadb
          docker run --rm mariadb-test mariadb --version  # Test MariaDB version

      - name: Log in to GHCR
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push MariaDB Image (Development)
        if: github.ref == 'refs/heads/development'
        run: |
          docker tag mariadb-test ghcr.io/${{ github.repository }}:mariadb-dev-latest
          docker push ghcr.io/${{ github.repository }}:mariadb-dev-latest

      - name: Push MariaDB Image (Master Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag mariadb-test ghcr.io/${{ github.repository }}:mariadb-${VERSION}
          docker tag mariadb-test ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:mariadb-${VERSION}
          docker push ghcr.io/${{ github.repository }}:latest
