name: Build & Push PHP-FPM Docker Image

on:
  push:
    branches:
      - development
    paths:
      - 'resources/docker/php-fpm/Dockerfile'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build PHP-FPM Image
        run: |
          docker build -t php-fpm-test ./resources/docker/php-fpm
          docker run --rm php-fpm-test php -v  # Basic test

      - name: Log in to GHCR
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push PHP-FPM Image (Development)
        if: github.ref == 'refs/heads/development'
        run: |
          docker tag php-fpm-test ghcr.io/${{ github.repository }}:php-fpm-dev-latest
          docker push ghcr.io/${{ github.repository }}:php-fpm-dev-latest

      - name: Push PHP-FPM Image (Master Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag php-fpm-test ghcr.io/${{ github.repository }}:php-fpm-${VERSION}
          docker tag php-fpm-test ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:php-fpm-${VERSION}
          docker push ghcr.io/${{ github.repository }}:latest
