name: Build & Push Nginx Docker Image

on:
  push:
    branches:
      - development
    paths:
      - 'resources/docker/nginx/Dockerfile'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Nginx Image
        run: |
          docker build -t nginx-test ./resources/docker/nginx
          docker run --rm nginx-test nginx -t  # Test Nginx config

      - name: Log in to GHCR
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Nginx Image (Development)
        if: github.ref == 'refs/heads/development'
        run: |
          docker tag nginx-test ghcr.io/${{ github.repository }}:nginx-dev-latest
          docker push ghcr.io/${{ github.repository }}:nginx-dev-latest

      - name: Push Nginx Image (Master Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag nginx-test ghcr.io/${{ github.repository }}:nginx-${VERSION}
          docker tag nginx-test ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:nginx-${VERSION}
          docker push ghcr.io/${{ github.repository }}:latest
