name: Frontend Testing

on:
  pull_request:
    branches:
      - development

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node: ['14', '16', '18']
    name: Node ${{ matrix.node }} build testing
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
      - name: Try to build the assets
        run: yarn build
