<?php

declare(strict_types=1);

$repoRoot = dirname(__DIR__, 2);
$modules  = $repoRoot . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR . 'modules';
$testsDir = $repoRoot . DIRECTORY_SEPARATOR . 'tests';

if ( ! is_dir($modules)) {
    fwrite(STDERR, "Cannot locate modules directory: {$modules}\n");
    exit(1);
}

$testFiles = [];
$riiTests  = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($testsDir));
/** @var SplFileInfo $testFile */
foreach ($riiTests as $testFile) {
    if ($testFile->isFile() && substr($testFile->getFilename(), -8) === 'Test.php') {
        $testFiles[] = strtolower($testFile->getFilename());
    }
}

$controllerRows = [];
$modelRows      = [];

$riiModules = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($modules));
/** @var SplFileInfo $moduleFile */
foreach ($riiModules as $moduleFile) {
    if ( ! $moduleFile->isFile() || substr($moduleFile->getFilename(), -4) !== '.php') {
        continue;
    }

    $path      = $moduleFile->getPathname();
    $shortName = pathinfo($moduleFile->getFilename(), PATHINFO_FILENAME);
    $baseName  = strtolower($shortName);

    if (strpos($path, DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR) !== false) {
        $token   = strtolower(str_replace('_', '', $shortName));
        $covered = false;
        foreach ($testFiles as $tf) {
            if (strpos($tf, $token) !== false && strpos($tf, 'controllertest.php') !== false) {
                $covered = true;
                break;
            }
        }
        $controllerRows[] = [
            'file'     => substr($path, strlen($repoRoot) + 1),
            'expected' => $token . ' + ControllerTest',
            'covered'  => $covered,
        ];
    }

    if (strpos($path, DIRECTORY_SEPARATOR . 'models' . DIRECTORY_SEPARATOR) !== false) {
        $normalized = preg_replace('/^mdl_/', '', $baseName);
        $covered    = false;
        foreach ($testFiles as $tf) {
            if (strpos($tf, $normalized) !== false) {
                $covered = true;
                break;
            }
        }
        $modelRows[] = [
            'file'       => substr($path, strlen($repoRoot) + 1),
            'token'      => $normalized,
            'covered'    => $covered,
        ];
    }
}

usort($controllerRows, static fn($a, $b): int => strcmp($a['file'], $b['file']));
usort($modelRows, static fn($a, $b): int => strcmp($a['file'], $b['file']));

$controllersTotal   = count($controllerRows);
$controllersCovered = count(array_filter($controllerRows, static fn($r): bool => $r['covered']));
$modelsTotal        = count($modelRows);
$modelsCovered      = count(array_filter($modelRows, static fn($r): bool => $r['covered']));

$reportPath = $testsDir . DIRECTORY_SEPARATOR . 'COVERAGE_AUDIT.md';
$lines      = [];
$lines[]    = '# Coverage Audit (Controllers + Models)';
$lines[]    = '';
$lines[]    = '- Generated by `php tests/Scripts/AuditModuleCoverage.php`.';
$lines[]    = '- Date (UTC): ' . gmdate('Y-m-d H:i:s');
$lines[]    = '';
$lines[]    = '## Summary';
$lines[]    = '';
$lines[]    = sprintf('- Controllers: **%d / %d** covered by filename match.', $controllersCovered, $controllersTotal);
$lines[]    = sprintf('- Models: **%d / %d** covered by token match.', $modelsCovered, $modelsTotal);
$lines[]    = '';
$lines[]    = '## Uncovered Controllers (filename heuristic)';
$lines[]    = '';
foreach ($controllerRows as $row) {
    if ( ! $row['covered']) {
        $lines[] = '- `' . $row['file'] . '` (expected test file `' . $row['expected'] . '`)';
    }
}
$lines[] = '';
$lines[] = '## Uncovered Models (token heuristic)';
$lines[] = '';
foreach ($modelRows as $row) {
    if ( ! $row['covered']) {
        $lines[] = '- `' . $row['file'] . '` (expected token in test filename: `' . $row['token'] . '`)';
    }
}
$lines[] = '';
$lines[] = '> Note: This is a filename/token heuristic and should be used as a triage list, not a proof of behavioral completeness.';

file_put_contents($reportPath, implode(PHP_EOL, $lines) . PHP_EOL);

fwrite(STDOUT, "Coverage audit written to tests/COVERAGE_AUDIT.md\n");
fwrite(STDOUT, sprintf("Controllers covered: %d/%d\n", $controllersCovered, $controllersTotal));
fwrite(STDOUT, sprintf("Models covered: %d/%d\n", $modelsCovered, $modelsTotal));

exit(0);
